name: Semantic release

on:
  push:
    branches:
      - "master"

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cancel previous builds
        uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run python-semantic-release
        run: |
          git config --global user.name "semantic-release"
          git config --global user.email "semantic-release@localhost"
          pip install python-semantic-release
          semantic-release publish
